server:
  port: 8000

spring:
  datasource:
    url: jdbc:h2:./target/local_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: sa
    password:
  h2:
    console:
      enabled: true

#logging:
#  level:
#    org:
#      zalando:
#        logbook: TRACE